#!/usr/bin/env bash
# setup haproxy and lisseting to web1 and web2 server
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*
echo "ENABLED=1" > /etc/default/haproxy            
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 431243-web-01 54.158.192.143:80 check
   server 431243-web-01 54.152.58.19:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
